"""new fields in user model

Revision ID: 60276390d0a2
Revises: 386f5fda2628
Create Date: 2019-10-29 02:03:16.642056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60276390d0a2'
down_revision = '386f5fda2628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
